import { NextResponse } from 'next/server';

export async function GET(request: Request) {
  try {
    // Generate a simple SVG thumbnail
    const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg width="400" height="500" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:#667eea;stop-opacity:1" />
      <stop offset="100%" style="stop-color:#764ba2;stop-opacity:1" />
    </linearGradient>
  </defs>

  <rect width="400" height="500" fill="url(#grad1)"/>

  <rect x="30" y="50" width="340" height="400" fill="white" opacity="0.95" rx="10"/>

  <text x="200" y="120" font-family="Arial, sans-serif" font-size="24" font-weight="bold" text-anchor="middle" fill="#667eea">
    Digital Product
  </text>

  <text x="200" y="160" font-family="Arial, sans-serif" font-size="16" text-anchor="middle" fill="#666">
    Generated by AI Agent
  </text>

  <circle cx="200" cy="250" r="60" fill="#667eea" opacity="0.2"/>
  <circle cx="200" cy="250" r="40" fill="#667eea" opacity="0.4"/>
  <circle cx="200" cy="250" r="20" fill="#667eea"/>

  <text x="200" y="350" font-family="Arial, sans-serif" font-size="14" text-anchor="middle" fill="#999">
    Professional Design
  </text>

  <text x="200" y="380" font-family="Arial, sans-serif" font-size="14" text-anchor="middle" fill="#999">
    High Quality Content
  </text>

  <text x="200" y="410" font-family="Arial, sans-serif" font-size="14" text-anchor="middle" fill="#999">
    Ready for Distribution
  </text>
</svg>`;

    return new NextResponse(svg, {
      headers: {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'public, max-age=31536000, immutable',
      },
    });
  } catch (error) {
    console.error('Thumbnail generation error:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to generate thumbnail' },
      { status: 500 }
    );
  }
}
